logs/urls.py
from django.contrib import admin
from django.urls import path, include
from logs import views
from logs import forms

app_name = 'logs'
urlpatterns = [
  path('', views.top, name='top'),
  path('index/', views.index, name='index'),
  # path('log_form/<int:log_id>/', views.confirm_label, name='confirm_label'),
  path('log/', views.log, name='log'),
  path('log_form/', views.log_form, name='log_form'),
  path('log_form/edit/<int:log_id>', views.log_form_edit, name='log_form_edit'),
  
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),  # accountsアプリ
    # ユーザーが未認証の場合はサインアップにリダイレクト
    path('', lambda request: redirect('accounts:sign_in') if not request.user.is_authenticated else redirect('logs:index')),
    path('', include('logs.urls', namespace='logs')),
    path('suggestions/', include('suggestions.urls', namespace='suggestions')),
    path('proposals/', include('proposals.urls', namespace='proposals')),
]

proposals/urls.py
from django.contrib import admin
from django.urls import path, include
from proposals import views

app_name = 'proposals'
urlpatterns = [
  # path('', views.top, name='top'),
  # path('index/', views.index, name='index'),
  path('show/',views.show, name='show'),
  path('delete/<int:item_id>/', views.delete, name='delete'),

  
]

templates/sidebar.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Toggle Sidebar Example</title>
  <link rel="stylesheet" href="{% static 'sidebar.css' %}">
</head>
<body>

  <button>=</button>

  <div id="sidebar" class="sidebar">
    <span id="close-btn" class="close-btn">&times;</span> <!-- 閉じるボタン -->
    <h2>Sidebar</h2>
    <ul>
      <li><a href="{% url 'logs:index' %}">INDEX</a></li>
      <li><a href="{% url 'logs:log_form'%}">ログ入力</a></li>
      <li><a href="{% url 'proposals:show'%}">目標立案</a></li>
    </ul>
  </div>

  <script src="{% static 'sidebar.js' %}"></script>
</body>
</html>